namespace(
    name="lex_v2_universal_bot",
    description="Universal Lex V2 chatbot for amazon connect",
    region="us-east-1",
    roleArn="arn:aws:iam::842675979580:role/aws-service-role/lex.amazonaws.com/AWSServiceRoleForLexBots",
    dataPrivacy=namespace(childDirected=False),
    idleSessionTTLInSeconds=300,
    lambdaHooks=namespace(
        codeHookUri="arn:aws:lambda:<REGION>:<ACCOUNT_ID>:function:lex_lambda_hanlder",
        timeoutInSeconds=8,
        invocationLabel="$LETEST",
    ),
    alias=namespace(name="prod", description="Production alias"),
    locale=[
        namespace(
            localeId="en_US",
            nluIntentConfidenceThreshold=0.4,
            voiceSettings=namespace(voiceId="Joanna", engine="neural"),
            intents=[
                namespace(
                    name="LEX_CUSTOM_PHRASE_EN_US",
                    codeHook="fulfillmentCodeHook",
                    description="A intent with custom phrases to fulfill all type of custom requests in english",
                    sampleUtterances=[
                        "I need help with {CUSTOM_PHRASE}.",
                        "Can you help me with {CUSTOM_PHRASE}?",
                        "I'm having trouble with {CUSTOM_PHRASE}, help.",
                        "Please assist me on {CUSTOM_PHRASE}.",
                        "I require assistance for {CUSTOM_PHRASE}.",
                        "Help me out with {CUSTOM_PHRASE}, please.",
                        "What's the way to handle {CUSTOM_PHRASE}?",
                        "I need some help regarding {CUSTOM_PHRASE}.",
                        "Assist with my {CUSTOM_PHRASE} issue.",
                        "Tell me how to fix {CUSTOM_PHRASE}.",
                        "Support needed for {CUSTOM_PHRASE}.",
                        "I'm stuck on {CUSTOM_PHRASE}, can you help?",
                        "Guide me through {CUSTOM_PHRASE}.",
                        "I want help on {CUSTOM_PHRASE} now.",
                        "Problem with {CUSTOM_PHRASE}, need aid.",
                    ],
                ),
                namespace(
                    name="LEX_REPEATED_PHRASE_EN_US",
                    codeHook=["intentConfirmationSetting"],
                    description="A intent with repeat phrases to fulfill all type of repeat requests in english",
                    sampleUtterances=[
                        "Repeat yourself.",
                        "What did you say?",
                        "Can you say it once more?",
                        "Go over that again.",
                        "Repeat the previous.",
                        "Say it over again.",
                        "I didn't hear, repeat.",
                        "Repeat your last response.",
                        "Again, what was that?",
                        "Come again?",
                        "Redo that statement.",
                        "Repeat after me, no, you repeat.",
                        "Echo that back.",
                        "Run it by me again.",
                        "What was the last part?",
                    ],
                ),
            ],
            slotDefinitions=[
                namespace(
                    name="LEX_PRODUCT_TYPE_EN_US",
                    type="Custom",
                    description="Sample lex to capture product name",
                    slotConstraint="Optional",
                    slotType=namespace(
                        resolutionStrategy="TopResolution",
                        slotTypeValues=[
                            namespace(
                                sampleValue="Laptop",
                                synonyms=[
                                    "notebook",
                                    "computer",
                                    "macbook",
                                    "ultrabook",
                                ],
                            ),
                            namespace(
                                sampleValue="Smartphone",
                                synonyms=[
                                    "mobile",
                                    "cell phone",
                                    "android phone",
                                    "iphone",
                                ],
                            ),
                            namespace(
                                sampleValue="Tablet",
                                synonyms=["ipad", "android tablet", "tab"],
                            ),
                            namespace(
                                sampleValue="Headphones",
                                synonyms=[
                                    "earphones",
                                    "earbuds",
                                    "headset",
                                    "audio device",
                                ],
                            ),
                            namespace(
                                sampleValue="Smartwatch",
                                synonyms=["fitness watch", "wearable", "digital watch"],
                            ),
                            namespace(
                                sampleValue="Camera",
                                synonyms=["dslr", "mirrorless", "digital camera"],
                            ),
                        ],
                    ),
                ),
                namespace(
                    name="LEX_YES_NO_EN_US",
                    type="Custom",
                    description="Yes or No responses",
                    slotConstraint="Optional",
                    slotType=namespace(
                        resolutionStrategy="TopResolution",
                        slotTypeValues=[
                            namespace(
                                sampleValue="Yes",
                                synonyms=[
                                    "ya",
                                    "yeah",
                                    "yep",
                                    "sure",
                                    "affirmative",
                                    "ok",
                                    "okay",
                                    "of course",
                                    "yup",
                                    "indeed",
                                    "certainly",
                                ],
                            ),
                            namespace(
                                sampleValue="No",
                                synonyms=[
                                    "nope",
                                    "nah",
                                    "negative",
                                    "never",
                                    "not at all",
                                    "nuh-uh",
                                    "no way",
                                    "nay",
                                    "not",
                                    "not today",
                                ],
                            ),
                        ],
                    ),
                ),
                namespace(
                    name="LEX_CHANNEL_EN_US",
                    type="Custom",
                    description="Communication channel type",
                    slotConstraint="Optional",
                    slotType=namespace(
                        resolutionStrategy="TopResolution",
                        slotTypeValues=[
                            namespace(
                                sampleValue="SMS",
                                synonyms=["text", "message", "short message service"],
                            ),
                            namespace(
                                sampleValue="Call",
                                synonyms=["phone", "voice call", "telephone"],
                            ),
                            namespace(sampleValue="Email", synonyms=["mail", "e-mail"]),
                            namespace(
                                sampleValue="Chat",
                                synonyms=["messenger", "live chat", "online chat"],
                            ),
                        ],
                    ),
                ),
                namespace(
                    name="LEX_DTMF_EN_US",
                    type="Custom",
                    description="DTMF key pressed by the user",
                    slotConstraint="Optional",
                    slotType=namespace(
                        resolutionStrategy="TopResolution",
                        slotTypeValues=[
                            namespace(sampleValue="0", synonyms=["zero", "none"]),
                            namespace(sampleValue="1", synonyms=["one", "first"]),
                            namespace(sampleValue="2", synonyms=["two", "second"]),
                            namespace(sampleValue="3", synonyms=["three", "third"]),
                            namespace(sampleValue="4", synonyms=["four", "fourth"]),
                            namespace(sampleValue="5", synonyms=["five", "fifth"]),
                            namespace(sampleValue="6", synonyms=["six", "sixth"]),
                            namespace(sampleValue="7", synonyms=["seven", "seventh"]),
                            namespace(sampleValue="8", synonyms=["eight", "eighth"]),
                            namespace(sampleValue="9", synonyms=["nine", "ninth"]),
                        ],
                    ),
                ),
                namespace(
                    name="LEX_FIRST_NAME_EN_US_Built-in",
                    type="BuiltIn",
                    slotConstraint="Optional",
                    slotTypeId="AMAZON.FirstName",
                ),
                namespace(
                    name="LEX_LAST_NAME_EN_US_Built-in",
                    type="BuiltIn",
                    slotConstraint="Optional",
                    slotTypeId="AMAZON.LastName",
                ),
                namespace(
                    name="LEX_PHONE_NUMBER_EN_US_Built-in",
                    type="BuiltIn",
                    slotConstraint="Optional",
                    slotTypeId="AMAZON.PhoneNumber",
                ),
                namespace(
                    name="LEX_EMAIL_ADDRESS_EN_US_Built-in",
                    type="BuiltIn",
                    slotConstraint="Optional",
                    slotTypeId="AMAZON.EmailAddress",
                ),
                namespace(
                    name="LEX_NUMBER_EN_US_Built-in",
                    type="BuiltIn",
                    slotConstraint="Optional",
                    slotTypeId="AMAZON.Number",
                ),
                namespace(
                    name="LEX_CITY_EN_US_Built-in",
                    type="BuiltIn",
                    slotConstraint="Optional",
                    slotTypeId="AMAZON.City",
                ),
                namespace(
                    name="LEX_SPELLED_WORDS_EN_US_EXTENDED",
                    type="Extended",
                    description="Alphanumeric input",
                    slotConstraint="Optional",
                    slotType=namespace(
                        parentSlotTypeSignature="AMAZON.AlphaNumeric",
                        regexPattern="[A-Za-z]",
                    ),
                ),
            ],
        )
    ],
)
